#!/usr/bin/env python3
"""
digest_to_pdf.py — Generate a PDF version of the morning digest using PDFBolt.

Converts the digest HTML to a PDF and returns the file path.
Can also be used standalone to generate a PDF from raw HTML.

Usage:
    python3 digest_to_pdf.py --html "<h1>Digest</h1>..."   # from HTML string
    python3 digest_to_pdf.py --file /tmp/digest.html       # from HTML file

Requires PDFBOLT_API_KEY in /root/.hermes/.env
Free tier: 100 PDFs/month
"""

import subprocess, sys, json, urllib.request, urllib.error, os
from datetime import datetime, timezone

ENV_PATH = "/root/.hermes/.env"

def get_key():
    r = subprocess.run(["grep", "PDFBOLT_API_KEY", ENV_PATH], capture_output=True, text=True)
    line = r.stdout.strip().split("\n")[0]
    return line.split("=", 1)[1] if "=" in line else ""

def generate_pdf(html_content):
    """Generate a PDF from HTML content using PDFBolt API."""
    key = get_key()
    if not key:
        raise Exception("PDFBOLT_API_KEY not found in .env. Sign up at https://pdfbolt.com")
    
    import base64
    html_b64 = base64.b64encode(html_content.encode()).decode()
    
    url = "https://api.pdfbolt.com/v1/direct"
    payload = json.dumps({
        "html": html_b64,
        "format": "A4",
        "printBackground": True,
        "margin": {"top": "20mm", "bottom": "20mm", "left": "15mm", "right": "15mm"},
    }).encode()
    
    req = urllib.request.Request(
        url,
        data=payload,
        headers={
            "API-KEY": key,
            "Content-Type": "application/json",
        },
        method="POST",
    )
    
    with urllib.request.urlopen(req, timeout=30) as resp:
        pdf_bytes = resp.read()
    
    # Save to file
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    pdf_dir = "/root/Geeves/digests"
    os.makedirs(pdf_dir, exist_ok=True)
    pdf_path = f"{pdf_dir}/digest_{today}.pdf"
    
    with open(pdf_path, "wb") as f:
        f.write(pdf_bytes)
    
    return pdf_path

def build_digest_html():
    """Build a digest HTML page from today's Airtable data.
    
    This is a helper that pulls from Airtable and formats as HTML.
    The cron job LLM composes the content, so this is a fallback
    for standalone use.
    """
    today = datetime.now(timezone.utc).strftime("%A, %B %d, %Y")
    
    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
         color: #1a1a1a; max-width: 600px; margin: 0 auto; padding: 20px; }}
  h1 {{ color: #2563eb; font-size: 24px; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }}
  h2 {{ color: #374151; font-size: 18px; margin-top: 24px; }}
  .section {{ margin-bottom: 20px; padding: 12px; background: #f9fafb; border-radius: 8px; border-left: 4px solid #2563eb; }}
  .headline {{ margin-bottom: 8px; }}
  .headline a {{ color: #1e40af; text-decoration: none; }}
  .source {{ color: #6b7280; font-size: 13px; }}
  .footer {{ margin-top: 30px; padding-top: 12px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; }}
</style>
</head>
<body>
<h1>☀️ Geeves Morning Digest</h1>
<p style="color: #6b7280;">{today}</p>

<div class="section">
<h2>📰 UK News</h2>
<p><em>Top headlines from SerpApi Google News. Run news_fetch.py for live data.</em></p>
</div>

<div class="section">
<h2>🌤️ Weather</h2>
<p><em>Run weather_fetch.py for live data.</em></p>
</div>

<div class="section">
<h2>📈 Markets</h2>
<p><em>Run stocks_fetch.py for live data.</em></p>
</div>

<div class="section">
<h2>💡 On This Day</h2>
<p><em>Run fact_fetch.py for live data.</em></p>
</div>

<div class="footer">
<p>Generated by Geeves 🤖 | Data from Open-Meteo, yfinance, Wikipedia, SerpApi</p>
</div>
</body>
</html>"""
    return html

def main():
    html_content = None
    
    if "--html" in sys.argv:
        idx = sys.argv.index("--html")
        if idx + 1 < len(sys.argv):
            html_content = sys.argv[idx + 1]
    elif "--file" in sys.argv:
        idx = sys.argv.index("--file")
        if idx + 1 < len(sys.argv):
            with open(sys.argv[idx + 1]) as f:
                html_content = f.read()
    else:
        html_content = build_digest_html()
    
    if not html_content:
        print("Usage: python3 digest_to_pdf.py --html '<html>...' or --file path.html")
        return
    
    print("📄 Generating PDF digest...")
    try:
        pdf_path = generate_pdf(html_content)
        print(f"  ✅ PDF saved to: {pdf_path}")
        print(f"  Size: {os.path.getsize(pdf_path):,} bytes")
    except Exception as e:
        print(f"  ❌ PDF generation failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
